site_name: hololinked
site_url: https://docs.hololinked.dev
repo_url: https://github.com/hololinked-dev/hololinked
repo_name: hololinked
edit_uri: https://github.com/hololinked-dev/docs/edit/main/docs/

nav:
  - Home:
      - Introduction: index.md
      - Installation: introduction/installation.md
      - Resources: introduction/resources.md
      - Contributing: introduction/contributing.md
      - License: introduction/license.md
      - Protocol Use Cases: introduction/use-cases.md
      - Security Scan Overview: introduction/security-scanning.md
  - Handbook:
      - Expose Python Objects: beginners-guide/articles/servers.md
      - Using Clients: beginners-guide/articles/object-proxy.md
      - Using Properties:
          - Types: beginners-guide/articles/properties/index.md
          - Default Arguments: beginners-guide/articles/properties/arguments.md
          - Extending: beginners-guide/articles/properties/extending.md
      - Using Actions: beginners-guide/articles/actions.md
      - Using Events: beginners-guide/articles/events.md
      - Using State Machine: beginners-guide/articles/state-machine.md
      - Configuring Thing Class: beginners-guide/articles/thing.md
      - Serialization: beginners-guide/articles/serialization.md
      - Protocols:
          - General: beginners-guide/articles/protocols/general.md
          - HTTP: beginners-guide/articles/protocols/http.md
          - MQTT: beginners-guide/articles/protocols/mqtt.md
      - Security: beginners-guide/articles/security.md
  - API Reference:
      - Namespaces: api-reference/namespaces.md
      - Thing:
          - Thing: api-reference/thing/index.md
          - Log Handlers: api-reference/thing/logger.md
          - Meta: api-reference/thing/thing-meta.md
          - Bases:
              - Propertized: api-reference/thing/bases/propertized.md
              - RemoteInvokable: api-reference/thing/bases/remote-invokable.md
              - EventSource: api-reference/thing/bases/event-source.md
          - Descriptor Registries:
              - DescriptorRegistry: api-reference/thing/registries/descriptor-registry.md
              - PropertyRegistry: api-reference/thing/registries/property-registry.md
              - ActionRegistry: api-reference/thing/registries/actions-registry.md
              - EventRegistry: api-reference/thing/registries/events-registry.md
      - Property: api-reference/property/index.md
      - Actions:
          - action: api-reference/action/index.md
          - Bases: api-reference/action/bases/index.md
      - Events:
          - Event: api-reference/events/index.md
          - EventDispatcher: api-reference/events/event-dispatcher.md
      - StateMachine:
          - StateMachine: api-reference/state-machine/state-machine.md
          - BoundFSM: api-reference/state-machine/bound-fsm.md
      - RPC Server:
          - RPCServer: api-reference/rpc-server/rpc-server.md
          - Messaging Contracts:
              - RequestMessage: api-reference/rpc-server/messaging-contract/request-message.md
              - ResponseMessage: api-reference/rpc-server/messaging-contract/response-message.md
              - EventMessage: api-reference/rpc-server/messaging-contract/event-message.md
              - Headers: api-reference/rpc-server/messaging-contract/headers.md
              - Contexts: api-reference/rpc-server/messaging-contract/contexts.md
          - Brokers:
              - BaseZMQ: api-reference/rpc-server/brokers/base-zmq.md
              - AsyncZMQServer: api-reference/rpc-server/brokers/async-zmq-server.md
              - SyncZMQClient: api-reference/rpc-server/brokers/sync-zmq-client.md
              - AsyncZMQClient: api-reference/rpc-server/brokers/async-zmq-client.md
              - MessageMappedClientPool: api-reference/rpc-server/brokers/message-mapped-zmq-client-pool.md
              - EventPublisher: api-reference/rpc-server/brokers/event-publisher.md
              - EventConsumer: api-reference/rpc-server/brokers/event-consumer.md
          # - Schedulers:
          #     - Scheduler: api-reference/rpc-server/schedulers/scheduler.md
          #     - QueuedScheduler: api-reference/rpc-server/schedulers/queued-scheduler.md
          #     - ThreadedScheduler: api-reference/rpc-server/schedulers/threaded-scheduler.md
          #     - AsyncScheduler: api-reference/rpc-server/schedulers/async-scheduler.md
      - Clients:
          - ClientFactory: api-reference/clients/base.md
          - ObjectProxy: api-reference/clients/object-proxy.md
          # Security
          - Abstractions:
              - ConsumedThingAction: api-reference/clients/bases/cta.md
              - ConsumedThingProperty: api-reference/clients/bases/ctp.md
              - ConsumedThingEvent: api-reference/clients/bases/cte.md
              - SSE: api-reference/clients/bases/sse.md
              - Utils: api-reference/clients/bases/utils.md
      - Servers:
          - HTTP: api-reference/protocols/http/index.md
          - ZMQ: api-reference/protocols/zmq/index.md
          - MQTT: api-reference/protocols/mqtt/index.md
          - Security:
              - Bcrypt: api-reference/protocols/security/bcrypt.md
              - Argon2: api-reference/protocols/security/argon2.md
      - Configuration: api-reference/global-config.md
      - Serializers:
          - Serializers: api-reference/serializers/index.md
      - Thing Descriptions:
          - Interaction Affordances:
              - InteractionAffordance: api-reference/td/interaction_affordance/interaction_affordance.md
              - PropertyAffordance: api-reference/td/interaction_affordance/property_affordance.md
              - ActionAffordance: api-reference/td/interaction_affordance/action_affordance.md
              - EventAffordance: api-reference/td/interaction_affordance/event_affordance.md
          - DataSchema: api-reference/td/data_schema.md
          - Thing Model: api-reference/td/tm.md
          - Bases:
              - Schema: api-reference/td/bases/schema.md
  # Examples
  # - Examples:
  #     - Energy Meter: examples/energy-meter.md
  #     - Linear Stage: examples/linear-stage.md
  #     - Oscilloscope: examples/oscilloscope.md
  #     - Camera: examples/camera.md
  #     - ADC in Raspberry Pi: examples/adc.md
  # - Blog:
  #   - blog/index.md
  - Developer Notes:
      - Descriptors: design/descriptors.md
      - Property Descriptors: design/property-descriptors.md
      - Action Descriptors: design/action-descriptors.md
      - Event Descriptors: design/event-descriptors.md
      - Descriptor Registry: design/descriptor-registry.md
      - Metaclasses: design/metaclasses.md
      - State Machine: design/state-machine.md
      - Serialization: design/serialization.md
      - ZMQ RPC Layer: design/zmq.md
      - Hexagonal Architecture: design/hexagonal-architecture.md

theme:
  name: material
  custom_dir: overrides

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: yellow

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: brown
      accent: orange

  icon:
    repo: fontawesome/brands/github

  features:
    # editing the page
    - content.action.edit
    - content.action.view
    # search
    - search.suggest
    - search.highlight
    - search.share
    # code
    - content.code.copy
    - content.code.select
    - content.code.annotate
    # headers
    - announce.dismiss
    # footer
    - navigation.footer
    # navigation
    - navigation.tabs
    - navigation.path
    - navigation.prune
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - navigation.top

  font:
    text: IBM Plex Sans
    heading: Lexend
    code: Roboto Mono
    # Other useful fonts that we may use:
    # Lexend Deca, Recursive, Inter, Fira Sans, IBM Plex Sans,
    # Google Sans Code (Used for titles and headers), Funnel Sans, Comme

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - git-authors
  - search
  - macros
  - autorefs:
      resolve_closest: true
  # - blog
  # - social
  - mkdocstrings:
      handlers:
        python:
          options:
            # code base and inheritance
            allow_inspection: true
            show_bases: true
            show_inheritance_diagram: true
            # headings
            show_root_heading: true
            parameter_headings: true
            heading_level: 1
            show_category_heading: true
            # docstrings style
            docstring_style: numpy
            group_by_category: true
            # annotations
            modernize_annotations: true
            show_signature_annotations: true
            separate_signature: true

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - toc:
      toc_depth: 3

extra:
  social:
    - icon: fontawesome/solid/book
      link: https://github.com/hololinked-dev/examples
      name: examples repository
    # - icon: fontawesome/solid/table-list
    #   link: https://hololinked.dev/
    #   name: directory of device implementations
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/hololinked/
      name: pypi
    # - icon: fontawesome/brands/
    #   link: https://anaconda.org/conda-forge/hololinked
    #   name: anaconda
    # - icon: fontawesome/brands/git
    #   link: https://github.com/hololinked-dev/docs
    #   name: source code for docs
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/kEz87zqQXh
      name: discord group
    - icon: fontawesome/solid/envelope
      link: mailto:info@hololinked.dev?subject=Inquiry/Feedback%20about%20hololinked"
      name: email
    - icon: fontawesome/solid/globe
      link: https://hololinked.dev/
      name: project website containing non-documentation resources
    - icon: fontawesome/solid/circle-dollar-to-slot
      link: https://github.com/sponsors/VigneshVSV
      name: sponsor

copyright: >
  <div style="font-size: 0.9em; margin-top: 1em; max-width: 800px;">
  Â© BSD-3-Clause license, hololinked contributors. This website was written by humans. Leave us a star on 
  <a href="https://github.com/hololinked-dev/hololinked" style="color: orange; text-decoration: underline;">GitHub</a> 
  if you find this project useful! <br/>
  This website uses anonymized privacy friendly GDPR compliant cookie-less analytics.
  </div>

extra_css:
  - stylesheets/extra.css
  - https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@300;400;500;600;700&display=swap
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css

extra_javascript:
  - https://unpkg.com/mermaid@10.9.0/dist/mermaid.min.js
